#!/usr/bin/env python
# coding: utf-8

# # Week 6: Data Visualization Mastery with Seaborn

# In[70]:


## importing required libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


# In[71]:


## loading sales_data using 'pandas' read_csv library 

df = pd.read_csv(r"C:\Users\nithi\OneDrive\Desktop\DevelopersIntern\sales_data.csv")


# In[72]:


## displaying the dataframe

df


# In[73]:


## checking for null values

df.isnull().sum()


# In[74]:


## checking for data types of the columns

df.dtypes


# In[75]:


## extracting Month names from date column

df['Date'] = pd.to_datetime(df['Date'])

df['Month_names'] = df['Date'].dt.month_name()
month_order = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
]
monthly_sales = df.groupby('Month_names', sort='False')['Total_Sales'].sum()

monthly_sales = monthly_sales.reindex(month_order)


# ### Visualizations with different chart types and graphs

# In[76]:


## boxplot showing total_sales across region 

sns.barplot(df, x='Region', y = 'Total_Sales')


# ### Barplot showing that North region generated highest sales and West region generated lowest sales 

# In[77]:


## using count plot to display number of observations in each product 

sns.countplot(df, x = 'Product')


# ### From the count plot, it is observed that Tablets are the most frequently sold product, followed by Laptops. This indicates strong customer demand for Tablets.

# In[78]:


## Lineplot displaying Sales across months

sns.lineplot(x=monthly_sales.index, y = monthly_sales.values)


# ### It can be observed that Sales are highest in March and lowest in April Month.

# In[79]:


## plotting correlation matrix among numerical variables

corr = df[['Quantity', 'Price', 'Total_Sales']].corr()
sns.heatmap(corr, annot =True)


# In[ ]:


#### Price and Total_Sales are highly correlated 


# In[80]:


## plotting boxplot for Total_Sales by Product

sns.boxplot(df, x='Product', y = 'Total_Sales')
plt.title('Total Sales by Product')


# ### boxplot shows that Maximum sales are generated by 'Laptop' and minimum sales are generated by 'Headphones' 

# In[81]:


## Interactive bar plot showing Total_Sales across Region and Product

fig = px.bar(df, x='Product', y='Total_Sales', color='Region',
             title='Interactive Sales by Product and Region')
fig.show()


# In[ ]:





# In[ ]:




